name: Run Terraform tests
on:
  workflow_call:
    inputs:
      root-dir:
        description: The root directory in which to run Terragrunt
        type: string
        required: false
        default: cloud

concurrency:
  group: ${{ github.workflow }}-terraform-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform and Terragrunt
        env:
          # Latest versions as of 2022-10-15
          TFENV_VERSION: 1ccfddb22005b34eacaf06a9c33f58f14e816ec9  # commit date 2022-10-01
          TGENV_VERSION: dd720f62051bb748f75eee2d83d6768171d45830  # commit date 2020-04-18
          TERRAGRUNT_COMMONS_VERSION: v1.0.2-dev0
        run: |-
          git config --global advice.detachedHead false

          rm -rf /usr/local/bin/terraform

          git clone https://github.com/tfutils/tfenv.git ~/tfenv
          cd ~/tfenv
          git checkout "${TFENV_VERSION}"
          ln -s ~/tfenv/bin/* /usr/local/bin

          git clone https://github.com/cunymatthieu/tgenv.git ~/tgenv
          cd ~/tgenv
          git checkout "${TGENV_VERSION}"
          ln -s ~/tgenv/bin/* /usr/local/bin

          git clone https://github.com/logikal-io/terragrunt-commons.git \
            -b ${TERRAGRUNT_COMMONS_VERSION} ~/.terragrunt

          cd "${{ github.workspace }}"
          cd "${{ inputs.root-dir }}"
          tgenv install

      - name: Install tflint
        env:
          TFLINT_VERSION: v0.41.0
        run: |-
          download_url="https://github.com/terraform-linters/tflint/releases/download"
          wget "${download_url}/${TFLINT_VERSION}/tflint_linux_amd64.zip" \
            --progress=dot:giga -O ~/tflint.zip
          unzip ~/tflint.zip -d /usr/local/bin
          chmod +x /usr/local/bin/tflint

      - name: Validate configuration
        run: |-
          cd "${{ inputs.root-dir }}"
          terragrunt run-all validate --terragrunt-parallelism 1 --terragrunt-no-auto-init
