name: Run Python tests
on:
  workflow_call:
    inputs:
      python-version:
        description: The Python version to use
        type: number
        required: false
        default: 3.8
      requirements:
        description: The path to the requirements file
        type: string
        required: false
        default: requirements/dev.txt
      chrome-version:
        description: The Chrome and ChromeDriver version to install
        type: string
        required: false
      hadoop-version:
        description: The Hadoop version to install
        type: string
        required: false
      hadoop-gcs-connector-version:
        description: The Hadoop Google Cloud Storage connector version to install
        type: string
        required: false
      hadoop-aws-module-version:
        description: The Hadoop AWS module version to install
        type: string
        required: false
      aws-java-sdk-version:
        description: The AWS Java SDK bundle version that was used to compile the Hadoop AWS module
        type: string
        required: false

    secrets:
      GCP_TESTING_WORKLOAD_IDENTITY_PROVIDER:
        description: Full identifier of the GitHub workload identity pool provider in Google Cloud
        required: false
      GCP_TESTING_SERVICE_ACCOUNT:
        description: Email of the Google Cloud service account used for running tests
        required: false
      AWS_TESTING_ROLE:
        description: The ARN of the AWS role used for running tests
        required: false
      AWS_TESTING_REGION:
        description: The AWS region to use for authorization
        required: false

concurrency:
  group: ${{ github.workflow }}-python-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v1
        env:
          RUN_STEP: ${{ secrets.GCP_TESTING_SERVICE_ACCOUNT != '' }}
        if: env.RUN_STEP == 'true'
        with:
          workload_identity_provider: ${{ secrets.GCP_TESTING_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_TESTING_SERVICE_ACCOUNT }}

      - name: Authenticate to Amazon Web Services
        uses: aws-actions/configure-aws-credentials@v1
        env:
          RUN_STEP: ${{ secrets.AWS_TESTING_ROLE != '' }}
        if: env.RUN_STEP == 'true'
        with:
          aws-region: ${{ secrets.AWS_TESTING_REGION }}
          role-to-assume: ${{ secrets.AWS_TESTING_ROLE }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - uses: logikal-io/make-orb@v1.0.0
        with:
          requirements: ${{ inputs.requirements }}

      - uses: logikal-io/install-chrome@v1.0.0
        if: inputs.chrome-version != ''
        with:
          version: ${{ inputs.chrome-version }}

      - uses: logikal-io/install-hadoop@v1.0.0
        if: inputs.hadoop-version != ''
        with:
          version: ${{ inputs.hadoop-version }}
          gcs-connector-version: ${{ inputs.hadoop-gcs-connector-version }}
          aws-module-version: ${{ inputs.hadoop-aws-module-version }}
          aws-java-sdk-version: ${{ inputs.aws-java-sdk-version }}

      - name: Run pytest
        run: orb --command pytest

      - name: Upload pytest artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: pytest-artifacts
          path: /tmp/pytest-of-runner/
          if-no-files-found: ignore
          retention-days: 7
