name: Run Terraform tests
on:
  workflow_call:
    inputs:
      root-dir:
        description: The root directory in which to run Terragrunt
        type: string
        required: false
        default: cloud
      terragrunt-commons-version:
        description: The version of terragrunt-commons to use
        type: string
        required: false
        default: v3
      tfenv-version:
        description: The version of tgenv to use
        type: string
        required: false
        default: 1ccfddb22005b34eacaf06a9c33f58f14e816ec9  # commit 2022-10-01 / checked 2022-12-22
      tgenv-version:
        description: The version of tfenv to use
        type: string
        required: false
        default: dd720f62051bb748f75eee2d83d6768171d45830  # commit 2020-04-18 / checked 2022-12-22
      tflint-version:
        description: The version of tflint to use
        type: string
        required: false
        default: v0.43.0  # checked 2022-12-22

    secrets:
      TERRAFORM_CREDENTIALS_HOSTNAME:
        description: The Terraform Cloud/Enterprise hostname to use
        required: false
      TERRAFORM_CREDENTIALS_TOKEN:
        description: The Terraform Cloud/Enterprise API token to use
        required: false

concurrency:
  group: ${{ github.workflow }}-terraform-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform and Terragrunt
        run: |-
          git config --global advice.detachedHead false

          rm -rf /usr/local/bin/terraform

          git clone https://github.com/tfutils/tfenv.git ~/tfenv
          cd ~/tfenv
          git checkout "${{ inputs.tfenv-version }}"
          ln -s ~/tfenv/bin/* /usr/local/bin

          git clone https://github.com/cunymatthieu/tgenv.git ~/tgenv
          cd ~/tgenv
          git checkout "${{ inputs.tgenv-version }}"
          ln -s ~/tgenv/bin/* /usr/local/bin

          git clone https://github.com/logikal-io/terragrunt-commons.git \
            -b "${{ inputs.terragrunt-commons-version }}" ~/.terragrunt

          cd "${{ github.workspace }}"
          cd "${{ inputs.root-dir }}"
          echo "Installing Terragrunt at '$(pwd)'"
          tgenv install

      - name: Install tflint
        run: |-
          download_url="https://github.com/terraform-linters/tflint/releases/download"
          wget "${download_url}/${{ inputs.tflint-version }}/tflint_linux_amd64.zip" \
            --progress=dot:giga -O ~/tflint.zip
          unzip ~/tflint.zip -d /usr/local/bin
          chmod +x /usr/local/bin/tflint

      - name: Validate configuration
        env:
          TERRAGRUNT_USE_CREDENTIALS: false
          CREDENTIALS_HOSTNAME: ${{ secrets.TERRAFORM_CREDENTIALS_HOSTNAME || 'app.terraform.io' }}
          CREDENTIALS_TOKEN: ${{ secrets.TERRAFORM_CREDENTIALS_TOKEN }}
        run: |-
          if [[ -n "${CREDENTIALS_TOKEN}" ]]; then
            hostname="$(echo "${CREDENTIALS_HOSTNAME}" | sed 's/\./_/g' | sed 's/-/__/g')"
            export "TF_TOKEN_${hostname}"="${CREDENTIALS_TOKEN}"
          fi
          cd "${{ inputs.root-dir }}"
          terragrunt run-all validate --terragrunt-parallelism 1
