name: Run Terraform tests
on:
  workflow_call:
    inputs:
      root-dir:
        description: The root directory in which to run Terragrunt
        type: string
        required: false
        default: cloud
      terragrunt-commons-version:
        description: The version of terragrunt-commons to use
        type: string
        required: false
        default: v3
      tfenv-version:
        description: The version of tfenv to use
        type: string
        required: false
        default: 1ccfddb22005b34eacaf06a9c33f58f14e816ec9  # commit 2022-10-01 / checked 2023-06-24
      tgenv-version:
        description: The version of tgenv to use
        type: string
        required: false
        default: dc65a8cd6d13eb1f69b5a04a0ba6fe1c68cd0627  # commit 2023-04-28 / checked 2023-10-16
      tflint-version:
        description: The version of tflint to use
        type: string
        required: false
        default: v0.47.0  # commit 2023-06-18 / checked 2023-06-24

    secrets:
      TERRAFORM_CREDENTIALS_HOSTNAME:
        description: The Terraform Cloud/Enterprise hostname to use
        required: false
      TERRAFORM_CREDENTIALS_TOKEN:
        description: The Terraform Cloud/Enterprise API token to use
        required: false

concurrency:
  group: ${{ github.workflow }}-terraform-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: logikal-io/run-logikal-playbook@v1
        with:
          roles: terraform
          vars: '{
            "tfenv_version": "${{ inputs.tfenv-version }}",
            "tgenv_version": "${{ inputs.tgenv-version }}",
            "terragrunt_commons_version": "${{ inputs.terragrunt-commons-version }}",
            "tflint_version": "${{ inputs.tflint-version }}",
          }'

      - name: Install Terragrunt
        working-directory: ${{ inputs.root-dir }}
        run: tgenv install

      - name: Validate configuration
        working-directory: ${{ inputs.root-dir }}
        env:
          TERRAGRUNT_USE_CREDENTIALS: false
          CREDENTIALS_HOSTNAME: ${{ secrets.TERRAFORM_CREDENTIALS_HOSTNAME || 'app.terraform.io' }}
          CREDENTIALS_TOKEN: ${{ secrets.TERRAFORM_CREDENTIALS_TOKEN }}
        run: |-
          if [[ -n "${CREDENTIALS_TOKEN}" ]]; then
            hostname="$(echo "${CREDENTIALS_HOSTNAME}" | sed 's/\./_/g' | sed 's/-/__/g')"
            export "TF_TOKEN_${hostname}"="${CREDENTIALS_TOKEN}"
          fi
          terragrunt run-all validate --terragrunt-parallelism 1
