name: Run Python tests
on:
  workflow_call:
    inputs:
      python-version:
        description: The Python version to use
        type: number
        required: false
        default: 3.8
      requirements:
        description: The path to the requirements file
        type: string
        required: false
        default: requirements/dev.txt
      chrome-version:
        description: The Chrome and ChromeDriver version to install
        type: string
        required: false

    secrets:
      TESTING_WORKLOAD_IDENTITY_PROVIDER:
        description: Full identifier of the GitHub workload identity pool provider in Google Cloud
        required: false
      TESTING_SERVICE_ACCOUNT:
        description: Email of the Google Cloud service account used for running tests
        required: false

concurrency:
  group: ${{ github.workflow }}-python-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        env:
          RUN_STEP: ${{ secrets.TESTING_SERVICE_ACCOUNT != '' }}
        if: env.RUN_STEP == 'true'
        with:
          workload_identity_provider: ${{ secrets.TESTING_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.TESTING_SERVICE_ACCOUNT }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - uses: logikal-io/make-orb@v1.0.0
        with:
          requirements: ${{ inputs.requirements }}

      - uses: logikal-io/install-chrome@v1.0.0
        if: inputs.chrome-version != ''
        with:
          version: ${{ inputs.chrome-version }}

      - name: Run pytest
        run: orb --command pytest

      - name: Upload pytest artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: pytest-artifacts
          path: /tmp/pytest-of-runner/
          if-no-files-found: ignore
          retention-days: 7
