name: Update floating tag
on:
  workflow_call:

concurrency: ${{ github.workflow }}-publish-${{ github.ref }}

jobs:
  update-tag:
    name: Update tag
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Update tag
        run: |-
          echo "Version: ${GITHUB_REF_NAME}"
          major_version=$(echo ${GITHUB_REF_NAME} | grep -o '^v[0-9]*')
          echo "Major version: ${major_version}"
          latest_version=$( \
            git tag --list --sort=version:refname | grep "^${major_version}\." | tail -n 1 \
          )

          if [[ ! ${latest_version} ]]; then
            echo "Invalid tag"
            exit 1
          fi

          echo "Setting tag ${major_version} to ${latest_version}"
          git tag --force "${major_version}" "${latest_version}"
          git push --force --tags
